version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tournament-postgres
    environment:
      POSTGRES_DB: tournament_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tournament-network

  backend:
    build: .
    container_name: tournament-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tournament_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - tournament-network

networks:
  tournament-network:
    driver: bridge

volumes:
  postgres_data: 